language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖
    - themes/icarus/node_modules

# S: Build Lifecycle
install:
  - cd themes/icarus
  - npm install
  - cd ../..
  - npm install -g hexo-cli
  - npm install

#script:
#  - hexo clean
#  - hexo g
#  - hexo algolia
#  - hexo deploy
script:
  - hexo generate # generate static file

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GH_TOKEN
  on:
    branch: master
  local-dir: public
# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master